import { NextRequest, NextResponse } from "next/server"
import ReactPDF, { Document, Page, Text, View, StyleSheet, renderToStream } from "@react-pdf/renderer"

const styles = StyleSheet.create({
    page: { flexDirection: "column", backgroundColor: "#E4E4E4", padding: 30 },
    section: { margin: 10, padding: 10, flexGrow: 1 },
    title: { fontSize: 24, marginBottom: 10 },
    text: { fontSize: 12 },
})

const MyDocument = () => (
    <Document>
        <Page size="A4" style={styles.page} >
            <View style={styles.section}>
                <Text style={styles.title}> My Portfolio </Text>
                < Text style={styles.text} > Generated by PortaForge </Text>
            </View>
        </Page>
    </Document>
)

export async function POST(
    req: NextRequest,
    { params }: { params: Promise<{ id: string }> }
) {
    const { id } = await params
    const stream = await renderToStream(<MyDocument />)

    return new NextResponse(stream as unknown as BodyInit, {
        headers: {
            "Content-Type": "application/pdf",
            "Content-Disposition": `attachment; filename="portfolio-${id}.pdf"`,
        },
    })
}
