export const templates = [
    {
        id: "minimal-1",
        name: "Mono",
        category: "Minimal",
        description: "Clean, monochromatic design for writers and strategists.",
        image: "https://images.unsplash.com/photo-1494438639946-1ebd1d20bf85?auto=format&fit=crop&w=800&q=80",
        tags: ["Minimal", "Blog", "Text-focused"],
    },
    {
        id: "creative-1",
        name: "Vibrant",
        category: "Creative",
        description: "Bold colors and large typography for designers.",
        image: "https://images.unsplash.com/photo-1558655146-d09347e92766?auto=format&fit=crop&w=800&q=80",
        tags: ["Creative", "Portfolio", "Bold"],
    },
    {
        id: "photo-1",
        name: "Lens",
        category: "Photography",
        description: "Full-width imagery to showcase your best shots.",
        image: "https://images.unsplash.com/photo-1452587925148-ce544e77e70d?auto=format&fit=crop&w=800&q=80",
        tags: ["Photography", "Gallery", "Visual"],
    },
    {
        id: "dev-1",
        name: "Terminal",
        category: "Developer",
        description: "Dark mode, code snippets, and tech stack focus.",
        image: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=800&q=80",
        tags: ["Developer", "Dark Mode", "Tech"],
    },
    {
        id: "minimal-2",
        name: "Air",
        category: "Minimal",
        description: "Spacious layout with subtle typography.",
        image: "https://images.unsplash.com/photo-1486312338219-ce68d2c6f44d?auto=format&fit=crop&w=800&q=80",
        tags: ["Minimal", "Clean", "Light"],
    },
    {
        id: "creative-2",
        name: "Neon",
        category: "Creative",
        description: "High contrast dark mode with neon accents.",
        image: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=800&q=80",
        tags: ["Creative", "Dark", "Neon"],
    },
]
